version: '3'
services:
  db:
    image: postgres
    hostname:
      db
    volumes:
     - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: SUp3r-pass*DB
      POSTGRES_DB: rust

volumes:
  postgres:
